name: CMake on a single platform
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  BUILD_TYPE: Release
  WX_VERSION: "3.2.9" # Specify the version you want
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache wxWidgets
        id: cache-wx
        uses: actions/cache@v3
        with:
          path: ~/wxWidgets
          key: wxwidgets-${{ env.WX_VERSION }}-${{ runner.os }}

      - name: Install wxWidgets dependencies
        if: steps.cache-wx.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev

      - name: Build wxWidgets from source
        if: steps.cache-wx.outputs.cache-hit != 'true'
        run: |
          cd ~
          wget https://github.com/wxWidgets/wxWidgets/releases/download/v${{ env.WX_VERSION }}/wxWidgets-${{ env.WX_VERSION }}.tar.bz2
          tar -xf wxWidgets-${{ env.WX_VERSION }}.tar.bz2
          cd wxWidgets-${{ env.WX_VERSION }}
          mkdir build-release
          cd build-release
          ../configure --prefix=$HOME/wxWidgets --disable-shared --enable-unicode --with-gtk=3
          make -j$(nproc)
          make install

      - name: Set wxWidgets environment
        run: echo "$HOME/wxWidgets/bin" >> $GITHUB_PATH

      - name: Configure CMake
        run: |
          export PATH=$HOME/wxWidgets/bin:$PATH
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DwxWidgets_CONFIG_EXECUTABLE=$HOME/wxWidgets/bin/wx-config

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
